#!/bin/bash

read -p "Enter file or directory: " path

if [ -d "$path" ]
then
	echo "$path is directory"
elif [ -f "$path" ]
then
	echo "$path is file"
else
	echo "$path is neither file, nor directory"
fi
