#!/bin/bash

read -p "Enter file or directory: " path

if [ -d "$path" ]
then
	echo "Given is directory"
elif [ -f "$path" ]
then
	echo "Given is file"
else
	echo "Given is neither file, nor directory"
fi
